/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'pricing-plans': PricingPlan;
    quotes: Quote;
    media: Media;
    products: Product;
    'product-content': ProductContent;
    'success-cases': SuccessCase;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-content': ProductContentSelect<false> | ProductContentSelect<true>;
    'success-cases': SuccessCasesSelect<false> | SuccessCasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('es' | 'ca' | 'en' | 'zh')
    | ('es' | 'ca' | 'en' | 'zh')[];
  globals: {
    'main-menu': MainMenu;
  };
  globalsSelect: {
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
  };
  locale: 'es' | 'ca' | 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Crea landings con el editor visual: arrastra componentes desde la paleta de la izquierda, configúralos en el panel de la derecha. URL pública: /<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Sin barras, en minúsculas. La URL final será /<slug>.
   */
  slug: string;
  status: 'draft' | 'published';
  puckData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Opcional. Si lo dejas vacío se usa el título de la página.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cada plan se conecta con su producto del catálogo y define lo que el cliente puede configurar en /precios/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  productSlug:
    | 'dealer'
    | 'exportaciones'
    | 'crm4you'
    | 'contact-center'
    | 'spyne'
    | 'motorflash-message'
    | 'motorflash-mobile-tracking'
    | 'ia'
    | 'soluciones-web'
    | 'marketing-digital'
    | 'portal-publicacion'
    | 'lead-factory'
    | 'soluciones-fabricantes'
    | 'motorflash-renting'
    | 'motorflash-connect'
    | 'apex';
  productName: string;
  /**
   * Aparece arriba del configurador. Texto plano.
   */
  introText?: string | null;
  /**
   * Escríbelo directamente en euros (p. ej. 199 o 199,50).
   */
  basePriceCents: number;
  currency: 'EUR' | 'USD';
  billingCycle: 'month' | 'year' | 'one_off';
  enabled?: boolean | null;
  /**
   * Inputs que verá el cliente: número de licencias, módulos opcionales, tier básico/pro/enterprise…
   */
  items?:
    | {
        /**
         * Ej. "licenses", "tier".
         */
        itemKey: string;
        label: string;
        helpText?: string | null;
        type: 'number' | 'select' | 'checkbox';
        /**
         * Escríbelo en euros. Numérico → precio por unidad. Casilla → precio cuando está marcada. Desplegable → déjalo en 0; el precio va dentro de cada opción.
         */
        unitPriceCents?: number | null;
        required?: boolean | null;
        numberMin?: number | null;
        numberMax?: number | null;
        numberDefault?: number | null;
        /**
         * Texto en singular. Se mostrará al cliente como "29,00 € / licencia".
         */
        numberUnit?: string | null;
        selectOptions?:
          | {
              value: string;
              label: string;
              /**
               * Cuota mensual de esta opción.
               */
              priceCents: number;
              /**
               * Coste de arranque que se cobra una sola vez al contratar esta opción. Déjalo en 0 si no hay setup.
               */
              setupCents?: number | null;
              isDefault?: boolean | null;
              id?: string | null;
            }[]
          | null;
        checkboxDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solicitudes enviadas desde el configurador público de /precios/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  productSlug: string;
  productName: string;
  contactName: string;
  email: string;
  companyName?: string | null;
  phone?: string | null;
  message?: string | null;
  selectedItems?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totalCents: number;
  currency: 'EUR' | 'USD';
  billingCycle: 'month' | 'year' | 'one_off';
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  contactedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imágenes que se usan en productos, casos de éxito y páginas. Sube en alta resolución; las miniaturas se generan automáticamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe la imagen para accesibilidad y SEO. Ej. "Logotipo Jarmauto" o "Equipo Motorflash 2026".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Catálogo de productos del menú, fichas y home. Se edita un único registro por producto; el orden lo controla "menuOrder".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Identificador único. Define la URL: /servicios/{slug}.
   */
  slug:
    | 'dealer'
    | 'exportaciones'
    | 'crm4you'
    | 'contact-center'
    | 'spyne'
    | 'motorflash-message'
    | 'motorflash-mobile-tracking'
    | 'ia'
    | 'soluciones-web'
    | 'marketing-digital'
    | 'portal-publicacion'
    | 'lead-factory'
    | 'soluciones-fabricantes'
    | 'motorflash-connect'
    | 'apex';
  /**
   * Nombre del icono en Material Symbols Outlined. Ej. inventory_2, hub, dynamic_feed.
   */
  icon: string;
  /**
   * Posición en el menú y catálogo (números menores = antes). Recomendado dejar saltos de 10.
   */
  menuOrder: number;
  /**
   * Aplica el estilo destacado (fondo naranja) en el listado y carrusel.
   */
  highlight?: boolean | null;
  /**
   * Marca el producto como "próximamente" en su ficha.
   */
  placeholder?: boolean | null;
  /**
   * Se muestra como título en el listado, carrusel y CTAs.
   */
  name: string;
  /**
   * Variante corta que aparece en el dropdown del navbar y la línea de tiempo de productos.
   */
  menuLabel: string;
  /**
   * Frase corta de marketing que acompaña al nombre en cards y fichas.
   */
  tagline: string;
  /**
   * Título grande de la ficha del producto.
   */
  heroTitle: string;
  /**
   * Párrafo introductorio bajo el hero de la ficha.
   */
  intro: string;
  /**
   * Solo si quieres sustituir el icono naranja por una imagen real (ej. logo de marca).
   */
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Secciones internas (highlights, features, process, CTA) de cada ficha de producto. Una entrada por producto. Edita el contenido por idioma usando la pestaña superior del admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-content".
 */
export interface ProductContent {
  id: number;
  /**
   * Elige el producto al que pertenece este contenido. Solo puede haber una entrada por producto.
   */
  product: number | Product;
  /**
   * Texto opcional que aparece bajo el título y sobre la intro.
   */
  subtitle?: string | null;
  /**
   * Añade secciones en el orden en que las quieras mostrar. Tipos: Funcionalidades, Destacados, Proceso y CTA final.
   */
  sections?:
    | (
        | {
            title: string;
            lead: string;
            items: {
              /**
               * Ej. analytics, hub, sync_alt.
               */
              icon: string;
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title: string;
            lead: string;
            highlights: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlights';
          }
        | {
            title: string;
            steps: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            title: string;
            lead: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clientes que aparecen en /historias-de-exito. El orden lo controla "order". Edita los textos por idioma desde la pestaña superior.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-cases".
 */
export interface SuccessCase {
  id: number;
  /**
   * Identificador único (también el ancla #slug en la página).
   */
  slug: string;
  /**
   * Posición en el listado (números menores = antes). Recomendado dejar saltos de 10.
   */
  order: number;
  /**
   * Cómo se muestra el bloque de cita del cliente.
   */
  quoteVariant: 'dark' | 'light';
  /**
   * Colores y estilo tipográfico del banner del cliente. Se aplican igual en los 4 idiomas.
   */
  brandStyle: {
    primary: string;
    ink: string;
    /**
     * P. ej. linear-gradient(135deg, #0A0A0A 0%, #1F1F1F 55%, #4A4A4A 100%)
     */
    banner: string;
    /**
     * P. ej. tracking-[-0.02em] font-bold
     */
    wordmarkClass?: string | null;
  };
  /**
   * Si no rellenas el logo, se mostrará el wordmark con la tipografía de marca.
   */
  logo?: {
    /**
     * P. ej. /images/clients/jarmauto.png
     */
    src?: string | null;
    alt?: string | null;
    width?: number | null;
    height?: number | null;
  };
  /**
   * Nombre del cliente en mayúsculas, usado como heading interno.
   */
  brand: string;
  /**
   * Texto-logo que aparece en el banner si no hay logo subido.
   */
  wordmark: string;
  /**
   * Descripción corta bajo el wordmark. P. ej. "Grupo automoción · Madrid".
   */
  tagline: string;
  /**
   * Etiqueta lateral del banner. P. ej. "Cliente Premium · Ecosistema completo".
   */
  badge: string;
  headline: string;
  /**
   * Acepta <strong> para resaltar partes. No incluyas scripts.
   */
  introHtml: string;
  quote: string;
  author: string;
  stats: {
    /**
     * P. ej. +180%, 360°, 24h.
     */
    value: string;
    label: string;
    id?: string | null;
  }[];
  ecosystemTitle: string;
  ecosystemLead: string;
  ecosystemItems: {
    text: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-content';
        value: number | ProductContent;
      } | null)
    | ({
        relationTo: 'success-cases';
        value: number | SuccessCase;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  puckData?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  productSlug?: T;
  productName?: T;
  introText?: T;
  basePriceCents?: T;
  currency?: T;
  billingCycle?: T;
  enabled?: T;
  items?:
    | T
    | {
        itemKey?: T;
        label?: T;
        helpText?: T;
        type?: T;
        unitPriceCents?: T;
        required?: T;
        numberMin?: T;
        numberMax?: T;
        numberDefault?: T;
        numberUnit?: T;
        selectOptions?:
          | T
          | {
              value?: T;
              label?: T;
              priceCents?: T;
              setupCents?: T;
              isDefault?: T;
              id?: T;
            };
        checkboxDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  productSlug?: T;
  productName?: T;
  contactName?: T;
  email?: T;
  companyName?: T;
  phone?: T;
  message?: T;
  selectedItems?: T;
  totalCents?: T;
  currency?: T;
  billingCycle?: T;
  status?: T;
  contactedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  icon?: T;
  menuOrder?: T;
  highlight?: T;
  placeholder?: T;
  name?: T;
  menuLabel?: T;
  tagline?: T;
  heroTitle?: T;
  intro?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-content_select".
 */
export interface ProductContentSelect<T extends boolean = true> {
  product?: T;
  subtitle?: T;
  sections?:
    | T
    | {
        features?:
          | T
          | {
              title?: T;
              lead?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        highlights?:
          | T
          | {
              title?: T;
              lead?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              lead?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-cases_select".
 */
export interface SuccessCasesSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  quoteVariant?: T;
  brandStyle?:
    | T
    | {
        primary?: T;
        ink?: T;
        banner?: T;
        wordmarkClass?: T;
      };
  logo?:
    | T
    | {
        src?: T;
        alt?: T;
        width?: T;
        height?: T;
      };
  brand?: T;
  wordmark?: T;
  tagline?: T;
  badge?: T;
  headline?: T;
  introHtml?: T;
  quote?: T;
  author?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  ecosystemTitle?: T;
  ecosystemLead?: T;
  ecosystemItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configura los enlaces de la barra de navegación. Arrastra para reordenar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  /**
   * Cada item es un enlace en la barra. Si eliges "Submenú" se convierte en un desplegable.
   */
  items?:
    | {
        label: string;
        kind: 'link' | 'dropdown';
        /**
         * Ej. /precios, /contacto, /landings/black-friday o https://blog.motorflash.com
         */
        url?: string | null;
        newTab?: boolean | null;
        /**
         * Aparecen al desplegar el submenú. Mínimo 1.
         */
        children?:
          | {
              label: string;
              url: string;
              /**
               * Opcional. Ej. hub, dynamic_feed. Lista en fonts.google.com/icons
               */
              icon?: string | null;
              /**
               * Opcional. Aparece debajo del enlace en el menú desplegable.
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * El botón naranja a la derecha del menú. Déjalo vacío si no quieres botón.
   */
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        kind?: T;
        url?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}