/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'pricing-plans': PricingPlan;
    quotes: Quote;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'main-menu': MainMenu;
  };
  globalsSelect: {
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Crea landings y otras páginas con bloques arrastrables. Pulsa "Live Preview" arriba a la derecha para verlo en directo mientras editas. URL pública: /<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Sin barras, en minúsculas. La URL final será /<slug>.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Arrastra para reordenar. Cada bloque se renderiza uno tras otro en la página pública.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            icon?: string | null;
            title: string;
            subtitle?: string | null;
            /**
             * Hasta 2 botones. El primero será naranja, el segundo blanco.
             */
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            width?: ('narrow' | 'wide') | null;
            alignment?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            columns?: ('2' | '3' | '4') | null;
            features?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            title: string;
            description?: string | null;
            buttonLabel: string;
            buttonUrl: string;
            style?: ('orange' | 'dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * Elige los productos del catálogo que quieres mostrar en el carrusel.
             */
            productSlugs: (
              | 'dealer'
              | 'exportaciones'
              | 'crm4you'
              | 'contact-center'
              | 'spyne'
              | 'motorflash-message'
              | 'motorflash-mobile-tracking'
              | 'ia'
              | 'soluciones-web'
              | 'marketing-digital'
              | 'portal-publicacion'
              | 'lead-factory'
              | 'soluciones-fabricantes'
              | 'apex'
            )[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCarousel';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            /**
             * Ruta a la imagen (de /public, p. ej. /images/foo.png) o URL externa.
             */
            imageUrl?: string | null;
            imageSide?: ('left' | 'right') | null;
            imageAlt?: string | null;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
      )[]
    | null;
  /**
   * Opcional. Si lo dejas vacío se usa el título de la página.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Cada plan se conecta con su producto del catálogo y define lo que el cliente puede configurar en /precios/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  productSlug:
    | 'dealer'
    | 'exportaciones'
    | 'crm4you'
    | 'contact-center'
    | 'spyne'
    | 'motorflash-message'
    | 'motorflash-mobile-tracking'
    | 'ia'
    | 'soluciones-web'
    | 'marketing-digital'
    | 'portal-publicacion'
    | 'lead-factory'
    | 'soluciones-fabricantes'
    | 'apex';
  productName: string;
  /**
   * Aparece arriba del configurador. Texto plano.
   */
  introText?: string | null;
  /**
   * Escríbelo directamente en euros (p. ej. 199 o 199,50).
   */
  basePriceCents: number;
  currency: 'EUR' | 'USD';
  billingCycle: 'month' | 'year' | 'one_off';
  enabled?: boolean | null;
  /**
   * Inputs que verá el cliente: número de licencias, módulos opcionales, tier básico/pro/enterprise…
   */
  items?:
    | {
        /**
         * Ej. "licenses", "tier".
         */
        itemKey: string;
        label: string;
        helpText?: string | null;
        type: 'number' | 'select' | 'checkbox';
        /**
         * Escríbelo en euros. Numérico → precio por unidad. Casilla → precio cuando está marcada. Desplegable → déjalo en 0; el precio va dentro de cada opción.
         */
        unitPriceCents?: number | null;
        required?: boolean | null;
        numberMin?: number | null;
        numberMax?: number | null;
        numberDefault?: number | null;
        /**
         * Texto en singular. Se mostrará al cliente como "29,00 € / licencia".
         */
        numberUnit?: string | null;
        selectOptions?:
          | {
              value: string;
              label: string;
              /**
               * En euros.
               */
              priceCents: number;
              isDefault?: boolean | null;
              id?: string | null;
            }[]
          | null;
        checkboxDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solicitudes enviadas desde el configurador público de /precios/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  productSlug: string;
  productName: string;
  contactName: string;
  email: string;
  companyName?: string | null;
  phone?: string | null;
  message?: string | null;
  selectedItems?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totalCents: number;
  currency: 'EUR' | 'USD';
  billingCycle: 'month' | 'year' | 'one_off';
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  contactedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              icon?: T;
              title?: T;
              subtitle?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              columns?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productCarousel?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              productSlugs?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              imageUrl?: T;
              imageSide?: T;
              imageAlt?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  productSlug?: T;
  productName?: T;
  introText?: T;
  basePriceCents?: T;
  currency?: T;
  billingCycle?: T;
  enabled?: T;
  items?:
    | T
    | {
        itemKey?: T;
        label?: T;
        helpText?: T;
        type?: T;
        unitPriceCents?: T;
        required?: T;
        numberMin?: T;
        numberMax?: T;
        numberDefault?: T;
        numberUnit?: T;
        selectOptions?:
          | T
          | {
              value?: T;
              label?: T;
              priceCents?: T;
              isDefault?: T;
              id?: T;
            };
        checkboxDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  productSlug?: T;
  productName?: T;
  contactName?: T;
  email?: T;
  companyName?: T;
  phone?: T;
  message?: T;
  selectedItems?: T;
  totalCents?: T;
  currency?: T;
  billingCycle?: T;
  status?: T;
  contactedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configura los enlaces de la barra de navegación. Arrastra para reordenar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  /**
   * Cada item es un enlace en la barra. Si eliges "Submenú" se convierte en un desplegable.
   */
  items?:
    | {
        label: string;
        kind: 'link' | 'dropdown';
        /**
         * Ej. /precios, /contacto, /landings/black-friday o https://blog.motorflash.com
         */
        url?: string | null;
        newTab?: boolean | null;
        /**
         * Aparecen al desplegar el submenú. Mínimo 1.
         */
        children?:
          | {
              label: string;
              url: string;
              /**
               * Opcional. Ej. hub, dynamic_feed. Lista en fonts.google.com/icons
               */
              icon?: string | null;
              /**
               * Opcional. Aparece debajo del enlace en el menú desplegable.
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * El botón naranja a la derecha del menú. Déjalo vacío si no quieres botón.
   */
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        kind?: T;
        url?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}